language: php
dist: trusty
php: '7.0'
git:
  depth: 3
before_install:
  - composer init --name="temp/check" --description="just checking the json" --author="No One <no@one.example>" --type="application" --homepage="https://github.com/IDotD/Raid-Tiers" --require=idrinth/config-check:dev-master
script: "vendor/bin/check-config.php -vvv -w"
