language: php
dist: trusty
php: '7.0'
git:
  depth: 3
install:
  - mkdir ../tools
  - composer create-project idrinth/config-check --no-dev --stability=dev --remove-vcs --working-dir=../tools
script: php ..tools/check-config -vvv -w
